spring:
  profiles:
    active: local

  application:
    name: My Pet Project

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  thymeleaf:
    enabled: false

---
#spring:
#  profiles: local
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:digital-lab;DB_CLOSE_ON_EXIT=FALSE
##    name: digital_lab
#    platform: h2